
version: "3.0"
services:
  sonarqube:
    image: 'sonarqube:latest'
    restart: always
    ports:
      - '9001:9000'
    networks:
      - sonarnet
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'
      SONAR_JDBC_URL: 'jdbc:postgresql://db:5432/sonar'
      SONAR_JDBC_USERNAME: 'sonar'
      SONAR_JDBC_PASSWORD: 'sonar'
    depends_on:
      - db
    volumes:
      - ./extension:/opt/sonarqube/extensions/plugins/
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      #- sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: 'postgres:latest'
    restart: always
    networks:
      - sonarnet
    environment:
       POSTGRES_DB: 'sonar'
       POSTGRES_USER: 'sonar'
       POSTGRES_PASSWORD: 'sonar'
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
networks:
  sonarnet:
    driver: bridge

volumes:
 postgresql:
 postgresql_data:
 sonarqube_conf:
 sonarqube_data:
 sonarqube_extensions:
 sonarqube_logs:
